### ISSUE TITLE
No Hostname

### ISSUE THREAD

**Issue by Setsuneh** [MyTheValentinus/ssh-login-alert-telegram#2]
Hi,

I've manually changed on all my servers the hostname on the same way. On one of them, the deployment can't be done.. 
The file `/etc/hostname` is written with one line..

`/opt# sh /etc/profile.d/telegram-alert.sh
hostname: Name or service not known`

**EDIT**

I've this on tTelegram

> Connection from XXX as root on  (XXX)
 Date: 06 sept. 2017 22:17
 More informations: https://ipinfo.io/XXX (https://ipinfo.io/XXX)<

But there is no hostname, and it has no symbol or number..

**Comment by vdeville** [comment]
Hello
Thanks for your report.
What is you distribution and version of this ?
Thanks

**Comment by Setsuneh** [comment]
Hi,

Here is that you need, thanks :)

```
root@Pihole:~# uname -a
Linux Pihole 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) x86_64 GNU/Linux

```
```
root@Pihole:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.9 (jessie)
Release:	8.9
Codename:	jessie`
```

**Comment by vdeville** [comment]
Thanks, what's happening when you type this command `hostname -f` ?

 Thanks

**Comment by Setsuneh** [comment]
Hi,

`root@Pihole:~# hostname -f
hostname: Name or service not known
`

**Comment by vdeville** [comment]
Your system is very strange. On my PiHole i have hostname command. Can you try to install hostname package ?

**Comment by Setsuneh** [comment]
I don't understand why, and the package is already installed. The must is doing reinstall it I think

**Comment by vdeville** [comment]
Yes, i think. I'm waiting your feedback
