### ISSUE TITLE
Deploy failed with ZSH on CentOS

### ISSUE THREAD

**Issue by b-net** [MyTheValentinus/ssh-login-alert-telegram#5]
> 

ssh-login-alert-telegram]# ./deploy.sh
Deploying alerts...
Check if ZSH is installed..
ZSH is installed, deploy alerts to zshrc
./deploy.sh: line 12: /etc/zsh/zshrc: No such file or directory
Done!
>
i had to chmod +x deploy.sh to be able to run it and install zsh prior running it. 
i've changed the configuration file with the proper tokens and group ids but does not seems to be working. Im running it on a Centos 7

**Comment by b-net** [comment]
I just found whats wrong, on Centos 7 zshrc is not in: /etc/zsh/zshrc is on /etc/zshrc

**Comment by vdeville** [comment]
Hello @b-net, 

Thanks, ok i add this to the todo if user use Centos, have you installed zsh via the package manaer ?

Merci

**Comment by b-net** [comment]
yes, i installed via YUM

`yum install zsh`

and im running:

` cat /etc/redhat-release`

`CentOS Linux release 7.7.1908 (Core)`

**Comment by b-net** [comment]
Another question, if i may...
in the credentials you have 2 variables, 

`USERID=( USERIDn CHANNELIDn )`

I assume userid is the Token and the Channel ID is the group or chat. 

but at the end of each theres a "n" letter, do i need to leave it?

**Comment by vdeville** [comment]
The `USERID` variable contains all receivers (channels, users directly or groups) seprate by space. `n` is just to indicate that is a number (integer in case of telegam).

**Comment by b-net** [comment]
thanks !

So it should be something like this?

`USERID=( 0000000000:XXX0yyXyyyXyyyX0yXXXX-0yyy0y0X0XXyX -000000000 )`
`KEY="none"`

**Comment by vdeville** [comment]
No, your secret key must be put in `KEY` variable and your receivers une `USERID`.
```
USERID=( -100000000995  -100666660996 )
KEY="3987987987:AAGP-7qda0918xbbbbxxxxxxx-WnEQ-0k"
```

**Comment by b-net** [comment]
thats why it doesnt work... hehe.. Thanks! i'll give it a try...

**Comment by b-net** [comment]
it worked ! Thanks

**Comment by b-net** [comment]
It worked! Thanks

Perhaps you should put the example above or specify what is the USERID and KEY on the main description, i was a little confused on the terms, because Telegram calls them TOKEN and GROUP_ID or CHAT_ID.
Best Regards!
